package com.tofas.vehicleExpertize.constant;

public enum VehicleEquipments {

    //TODO: WHEN STATIC AND OPTIONAL EQUIPMENT INFORMATION IS TO BE RETRIEVED FROM AUTOROLA XML FILE,
    // THE NEW EQUIPMENT DATA SHOULD BE ADD HERE AS ENUM
    _SUNROOF(1L, "SUNROOF", "STANDARD"),
    _PANORAMA_ROOF(2L, "PANORAMIK TAVAN", "STANDARD"),
    _LEATHER(3L, "DERI", "STANDARD"),
    _VENTILATED_SEATS(4L, "SOĞUTMALI ÖN KOLTUKLAR", "STANDARD"),
    _HEATED_SEATS(5L, "ISITMALI ÖNKOLTUKLAR", "STANDARD"),
    _SOFT_CLOSE_DOORS(6L, "VAKUMLU KAPILAR", "STANDARD"),
    _REAR_PARKING_CAMERA(7L, "GERI GÖRÜŞ KAMERA", "STANDARD"),
    _FRONT_CAMERA(8L, "ÖN KAMERA", "STANDARD"),
    _360_CAMERA(9L, "360 DERECE KAMERA", "STANDARD"),
    _INTERNET_CONNECTION_INFO_SYSTEM(10L, "İNTERNET BAĞLANTISI", "STANDARD"),
    _XENON_LIGHTS(11L, "XENON FARLAR", "STANDARD"),
    _LED_LIGHTS(12L, "LED FARLAR", "STANDARD"),
    _PARKING_SENSORS(13L, "ARKA PARK SENSÖRLERI", "STANDARD"),
    _ADAPTIVE_CRUISE_CONTROL(14L, "ADAPTIF HIZ SABITLEME", "STANDARD"),
    _LINE_ASSIST(15L, "ŞERIT TAKIP YARDIMCISI", "STANDARD"),
    _NAVIGATION(16L, "NAVIGASYON", "STANDARD"),
    _BLIND_SPOT_ALARM(17L, "KÖR NOKTA YARDIMCISI", "STANDARD"),
    _INFOTAINMENT_SYSTEM(18L, "ARAÇ IÇI EĞLENCE SISTEMI", "STANDARD"),
    _BLUETOOTH(19L, "BLUETOOTH", "STANDARD"),
    _ELECTRICALLY_ADJUSTABLE_DRIVER_SEAT(20L, "ELEKTIRIKLI SÜRÜCÜ KOLTUĞU", "STANDARD"),
    _MEMORY_FOR_DRIVER_SEAT(21L, "SÜRÜCÜ KOLTUĞU IÇIN HAFIZA", "STANDARD"),
    _ELECTRICALLY_ADJUSTABLE_PASSENGER_SEAT(22L, "ELEKTIRIKLI YOLCU KOLTUĞU", "STANDARD"),
    _MEMORY_FOR_PASSENGER_SEAT(23L, "YOLCU KOLTUĞU IÇIN HAFIZA", "STANDARD"),
    _ELECTRIC_FOLDING_SIDE_MIRRORS(24L, "ELEKTRIKLI KATLANIR YAN AYNALAR", "STANDARD"),
    _7_SEATED(25L, "7 KIŞILIK", "STANDARD");

    private Long id;
    private String description;
    private String type;
    VehicleEquipments(Long id, String description, String type) {
        this.description = description;
        this.id = id;
        this.type = type;
    }

    public String getDescription() {
        return description;
    }

    public Long getId() {
        return id;
    }

    public String getType() {
        return type;
    }
}
