# ---------- AUTOROLA CONFIG --------------
server:
  port : 8085
  debug: true

spring:

  hibernate:
    hbm2ddl:
      auto=update:
  datasource:
    url: jdbc:postgresql://tf2postgredbtest01:5432/tfs_qa
    username: tfs_tkp
    password: Svmr70rmv
    driverClassName: org.postgresql.Driver
    hikari:
      pool-name: expertise-dbconnectionpool

  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      temp:
        use_jdbc_metadata_defaults=false:

autorola:
  user-credential:
    username: del
    password: del
  api-url:
    baseUrl: https://assets.fm.autorolaapis.com
    loginUrl: /login
    fileUrl: /v2/files
    vehicleUrl: /v2/vehicle
fya:
  user-credential:
    username: del
    password: del
  api-url:
    baseUrl: https://yolarkadasimapi.fiat.com.tr
    loginUrl: /mobile/api/login
    valuationUrl: /mobile/api/dynamic-valuation/valuation-result
